### ISSUE TITLE
Encountering issues with 2. Download assets

### ISSUE THREAD

**Issue by divinetechnique** [merazgasalim/prismic-repository-cloner#4]
First of all, thank you for this very useful tool. 

After running Prismic Migration Tool, I successfully completed step 1. Get assets list. 

On step 2. Download assets, encountering error shown below.  Am I doing something wrong?

Thank you!

TypeError: Cannot read properties of undefined (reading 'length')
    at handler (webpack-internal:///(api)/./pages/api/assets.js:40:49)
    at /Users/xxxx/repos/prismic-repository-cloner-main/node_modules/next/dist/compiled/next-server/pages-api.runtime.dev.js:21:3039
    at /Users/xxxx/repos/prismic-repository-cloner-main/node_modules/next/dist/server/lib/trace/tracer.js:133:36
    at NoopContextManager.with (/Users/xxxx/repos/prismic-repository-cloner-main/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/Users/xxxx/repos/prismic-repository-cloner-main/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
    at NoopTracer.startActiveSpan (/Users/xxxx/repos/prismic-repository-cloner-main/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18093)
    at ProxyTracer.startActiveSpan (/Users/xxxx/repos/prismic-repository-cloner-main/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18854)
    at /Users/xxxx/repos/prismic-repository-cloner-main/node_modules/next/dist/server/lib/trace/tracer.js:122:103
    at NoopContextManager.with (/Users/xxxx/repos/prismic-repository-cloner-main/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/Users/xxxx/repos/prismic-repository-cloner-main/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
    at NextTracerImpl.trace (/Users/xxxx/repos/prismic-repository-cloner-main/node_modules/next/dist/server/lib/trace/tracer.js:122:28)
    at K (/Users/xxxx/repos/prismic-repository-cloner-main/node_modules/next/dist/compiled/next-server/pages-api.runtime.dev.js:21:2970)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async U.render (/Users/xxxx/repos/prismic-repository-cloner-main/node_modules/next/dist/compiled/next-server/pages-api.runtime.dev.js:21:3827)
    at async DevServer.runApi (/Users/xxxx/repos/prismic-repository-cloner-main/node_modules/next/dist/server/next-server.js:554:9)

**Comment by aroldanju** [comment]
Hi there! 

Make sure that you have a valid token in the step of listing assets. I faced same issue and it was because I was having troubles with the password on getToken request.
